MAX_LENGTH_EMAIL = 254
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150

MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_MEASUREMENT = 64
MAX_LENGTH_RECIPE_NAME = 256
MAX_LENGTH_SLUG = 32
MAX_LENGTH_TAG = 32

MIN_COOKING_TIME = 1
MIN_INGREDIENTS_COUNT = 1
